apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: traffic-mlops
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30081
