version: "3.9"

services:
  traffic-api:
    build: .
    container_name: traffic-mlops-container

    ports:
      - "8000:8000"

    environment:
      MLFLOW_ALLOW_FILE_STORE: "true"
      PYTHONUNBUFFERED: "1"

    volumes:
      - ./models:/app/models
      - ./results:/app/results
      - ./monitoring:/app/monitoring
      - ./mlruns:/app/mlruns
      - ./data_versions:/app/data_versions
      - ./data:/app/data

    restart: unless-stopped


  traffic-drift-worker:
    build: .
    container_name: traffic-drift-worker-container

    command: python -u retrain_job.py

    environment:
      PYTHONUNBUFFERED: "1"
      MLFLOW_ALLOW_FILE_STORE: "true"

      DATA_PATH: "data/TrafficVolumeData.csv"
      MODEL_PATH: "models/best_model.pkl"
      STATE_PATH: "monitoring/drift_state.json"

      # Ngưỡng 100 quá thấp, dễ drift liên tục.
      # Tạm dùng 700 cho demo hợp lý hơn.
      MAE_THRESHOLD: "700"

      DRIFT_START_DATE: "2014-01-01"
      DRIFT_END_LIMIT: "2014-09-01"

      INITIAL_TRAIN_START: "2013-07-01"
      INITIAL_TRAIN_END: "2013-12-31"

      # Mỗi lần check/retrain theo cửa sổ 7 ngày
      CHECK_WINDOW_DAYS: "30"

      # Demo: 60 giây check 1 lần
      # Làm thật có thể đổi thành 3600 hoặc 86400
      CHECK_INTERVAL_SECONDS: "30"

      RUN_ONCE: "false"

    volumes:
      - ./models:/app/models
      - ./results:/app/results
      - ./monitoring:/app/monitoring
      - ./mlruns:/app/mlruns
      - ./data_versions:/app/data_versions
      - ./data:/app/data

    restart: unless-stopped