apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traffic-mlops

resources:
  - ../../base/namespace.yaml
  - ../../base/configmap.yaml
  - ../k3s/secret.k3s.example.yaml
  - ../../base/postgres.yaml
  - ../../base/minio.yaml
  - ../../base/mlflow.yaml
  - ../../base/traffic-api.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: traffic-api
    newName: docker.io/tannampham23/traffic-api
    newTag: v27
  - name: traffic-mlflow
    newName: docker.io/tannampham23/traffic-mlflow
    newTag: v1

patches:
  - path: ../k3s/patches/configmap.k3s.yaml
  - path: ../k3s/patches/postgres-storage.k3s.yaml
  - path: ../k3s/patches/minio-storage.k3s.yaml
  - path: ../k3s/patches/api-storage.k3s.yaml
  - path: ../k3s/patches/api-service.k3s.yaml
  - path: ../k3s/patches/infra-node-selector.k3s.yaml
  - path: ../k3s/patches/api-node-selector.k3s.yaml
