apiVersion: v1
kind: Secret
metadata:
  name: traffic-secrets
  namespace: traffic-mlops
type: Opaque
stringData:
  POSTGRES_PASSWORD: traffic_dev_password
  DATABASE_URL: postgresql+psycopg://traffic:traffic_dev_password@postgres:5432/traffic_management
  MLFLOW_BACKEND_STORE_URI: postgresql+psycopg2://traffic:traffic_dev_password@postgres:5432/mlflow
  AIRFLOW_SQL_ALCHEMY_CONN: postgresql+psycopg2://traffic:traffic_dev_password@postgres:5432/airflow
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin123
  AUTH_SECRET_KEY: replace-with-a-long-random-secret
  BOOTSTRAP_ADMIN_PASSWORD: admin123456
  INTERNAL_TRAINING_TOKEN: replace-with-a-long-random-internal-token
  AIRFLOW_SECRET_KEY: replace-with-a-long-random-airflow-secret
  AIRFLOW_ADMIN_PASSWORD: admin
