apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traffic-mlops

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - minio.yaml
  - mlflow.yaml
  - airflow.yaml
  - traffic-api.yaml
  - traffic-web.yaml

configMapGenerator:
  - name: airflow-dags
    namespace: traffic-mlops
    files:
      - traffic_region_training.py=airflow-dags/traffic_region_training.py

generatorOptions:
  disableNameSuffixHash: true
