apiVersion: v1
kind: Service
metadata:
  name: traffic-web
  namespace: traffic-mlops
spec:
  type: NodePort
  selector:
    app: traffic-web
  ports:
    - name: http
      port: 5173
      targetPort: 5173
      nodePort: 30073
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-web
  namespace: traffic-mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-web
  template:
    metadata:
      labels:
        app: traffic-web
    spec:
      containers:
        - name: traffic-web
          image: traffic-web:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: traffic-config
                  key: VITE_API_BASE_URL
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 10
            periodSeconds: 10
